### ISSUE TITLE
List all linodes and associated public ip address

### ISSUE THREAD

**Issue by nodesocket** [arodygin/linode-api-php#1]
We are looking at using your library for importing a list of all servers into https://commando.io from Linode.

We need to list all Linodes in an account, and then list each public ip address associated with each server. Can you provide an example of this? Can we use batch to prevent making an API request for each server?

**Comment by nodesocket** [comment]
Specially, can I get an example of calling:

https://github.com/arodygin/linode-api-php/blob/master/src/Linode/IpApi.php#L63

**Comment by nodesocket** [comment]
Nevermind, got it working.

**Comment by arodygin** [comment]
Great! Glad to hear it's working.
